version: '3'
services:
  app:
    image: "apps:${DOCKER_COMPOSE_APP_IMAGE_TAG:-calendarapp}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_FILE_BUILD_COMMAND: ${DOCKER_FILE_BUILD_COMMAND:-echo yarn workspace @app/calendarapp build}
        DOCKER_FILE_INSTALL_COMMAND: ${DOCKER_FILE_INSTALL_COMMAND:-python3 -m pip install 'psycopg2-binary>=2.8.5' && python3 -m pip install 'Django>=3.0.6'}
    ports:
      - "127.0.0.1:3003:3000"
    command: "${DOCKER_COMPOSE_START_APP_COMMAND:-yarn workspace @app/calendarapp start}"
    user: app
    volumes:
      - ./apps/:/home/app/apps
      - ./packages/:/home/app/packages
      - ./bin/:/home/app/bin
      - ./package.json:/home/app/package.json
    env_file: ./apps/calendarapp/.env
    networks:
      - app-network
  mongodb:
    image: mongo:4.2.5
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: main
    networks:
      - app-network
  postgresdb:
    image: postgres:13.0
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
